
x-default: &default
  user: 1000:1000
  # group_add:
  #   - 109
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Australia/Melbourne
  restart: unless-stopped

x-xarr: &xarr
  <<: *default
  networks:
    - xarr
  volumes:
    # - my_media:/mnt/media
    # - my_downloads:/mnt/downloads
    # - /mnt/media:/mnt/media
    # - /mnt/downloads:/mnt/downloads
    - ./media/:/mnt/media/
    - ./downloads/:/mnt/downloads/
  depends_on:
    - qbittorrent
    - jackett

services:

  qbittorrent:
    <<: *default
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    expose:
      - 8080:8080

  jackett:
    <<: *default
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /config/jackett:/config
    ports:
      - 9117:9117
    expose:
      - 9117:9117

  radarr:
    <<: *xarr
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./config/radarr:/config
    ports:
      - 7878:7878
    expose:
      - 7878:7878

  sonarr:
    <<: *xarr
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
    ports:
      - 8989:8989
    expose:
      - 8989:8989

  lidarr:
    <<: *xarr
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ./config/lidarr:/config
    ports:
      - 8686:8686
    expose:
      - 8686:8686

  bazarr:
    <<: *xarr
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ./config/bazarr:/config
    ports:
      - 6767:6767
    expose:
      - 6767:6767
    depends_on:
      - radarr
      - sonarr
      - lidarr

  jellyfin:
    <<: *default
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      # - my_media:/mnt/media/
      # - /mnt/media:/mnt/media/
      - ./media/:/mnt/media/
      - /etc/timezone:/etc/timezone:ro
      - ./config/jellyfin/etc:/etc/jellyfin
      - ./config/jellyfin/var-cache:/var/cache/jellyfin
      - ./config/jellyfin/var-lib:/var/lib/jellyfin
      - ./config/jellyfin/var-log:/var/log/jellyfin
    ports:
      - 8096:8096
    expose:
      - 8096:8096

networks:
  xarr:

# volumes:
#   my_media:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       # device: /mnt/media/
#       device: ./media/ ### Testing
#   my_downloads:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       # device: /mnt/downloads/
#       device: ./downloads/ ### Testing
